name: repository_size.yml
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: echo $(github.head_ref)
      - run: du -skh --exclude=".git"
