name: repository_size.yml
on: [ push ]

 jobs:
  build:
    runs-on: ubuntu-latest
    uses: actions/checkout@v4.1.1
    
    steps:
      - run: echo $(github.head_ref)
      - run: du -skh --exclude=".git"
            